cabal-version:      3.0
name:               flowforge-backend
version:            0.1.0.0
synopsis:           Typed Workflow & Business Process Platform
license:            NONE
author:             Pratham
maintainer:         pratham@example.com
build-type:         Simple

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        FlowForge.Domain.Types
        FlowForge.Domain.Error
        FlowForge.Domain.Authorization
        FlowForge.Domain.Validation
        FlowForge.Domain.Workflow
        FlowForge.Domain.Transition
        FlowForge.Application.Error
        FlowForge.Application.Ports
        FlowForge.Application.UseCases.Workflow
        FlowForge.Application.UseCases.Instance
        FlowForge.Infrastructure.Database
        FlowForge.Infrastructure.Repositories.Workflow
        FlowForge.Infrastructure.Repositories.Instance
        FlowForge.Infrastructure.Repositories.Audit
        FlowForge.Infrastructure.Transaction
        FlowForge.Config
        FlowForge.Infrastructure.Auth.Password
        FlowForge.Infrastructure.Repositories.User
        FlowForge.Application.UseCases.Auth
        FlowForge.Api.Types
        FlowForge.Api.Requests
        FlowForge.Api.Responses
        FlowForge.Api.Errors
        FlowForge.Api.Env
        FlowForge.Api.Auth
        FlowForge.Api.Routes
        FlowForge.Api.Handlers
        FlowForge.Api.Server
        FlowForge.Api.OpenAPI
    build-depends:
        base >= 4.18 && < 5,
        uuid,
        text,
        containers,
        postgresql-simple,
        resource-pool,
        time,
        mtl,
        transformers,
        bytestring,
        servant-server,
        servant,
        case-insensitive,
        servant-auth,
        servant-auth-server,
        servant-openapi3,
        openapi3,
        aeson,
        wai,
        wai-extra,
        warp,
        wai-cors,
        password,
        password-instances,
        http-types,
        lens,
        insert-ordered-containers
    hs-source-dirs:   src
    default-language: Haskell2010

executable flowforge-backend
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base >= 4.18 && < 5,
        flowforge-backend,
        bytestring,
        warp,
        servant-auth-server
    hs-source-dirs:   app
    default-language: Haskell2010

test-suite flowforge-backend-test
    import:           warnings
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    other-modules:
        FlowForge.Domain.AuthorizationSpec
        FlowForge.Domain.ValidationSpec
        FlowForge.Domain.WorkflowSpec
        FlowForge.Domain.TransitionSpec
        FlowForge.Application.UseCasesSpec
        FlowForge.Infrastructure.IntegrationSpec
        FlowForge.Api.IntegrationSpec
    build-depends:
        base >= 4.18 && < 5,
        flowforge-backend,
        hspec,
        QuickCheck,
        uuid,
        text,
        containers,
        postgresql-simple,
        resource-pool,
        time,
        mtl,
        transformers,
        bytestring,
        servant-server,
        servant,
        case-insensitive,
        servant-auth,
        servant-auth-server,
        servant-openapi3,
        openapi3,
        aeson,
        wai,
        wai-extra,
        warp,
        wai-cors,
        password,
        password-instances,
        http-types,
        lens,
        insert-ordered-containers,
        hspec-wai,
        hspec-wai-json
    build-tool-depends:
        hspec-discover:hspec-discover
